# Generated by Django 4.0 on 2024-02-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projcets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wireless_tech', models.BooleanField()),
                ('is_cloud_tech', models.BooleanField()),
                ('is_virtual_tech', models.BooleanField()),
                ('protection_class', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='R_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('appointment', models.CharField(max_length=255)),
            ],
        ),
    ]
