# Generated by Django 4.0 on 2024-02-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='projcets',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='profils.user'),
            preserve_default=False,
        ),
    ]
