# Generated by Django 4.0 on 2024-02-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0003_projcets_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projcets',
            name='is_cloud_tech',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projcets',
            name='is_virtual_tech',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projcets',
            name='is_wireless_tech',
            field=models.BooleanField(default=True),
        ),
    ]
