# Generated by Django 4.0 on 2024-02-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0004_alter_projcets_is_cloud_tech_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projcets',
            name='name_project',
            field=models.CharField(default='Тестовый', max_length=255),
        ),
    ]
